/**
 * P365 Outlook Add-in — MailApp Plug-in
 *
 * Auto-generates petroleum engineering calculation summaries as formatted
 * emails from P365 calculation results.
 *
 * Planned Features:
 *   - Insert pipe sizing summary into email body (HTML table)
 *   - Auto-generate RFI response with calculation attachments
 *   - P365 calculation snapshot to email (read-only results card)
 *   - Gas composition report via email
 *   - Well performance summary email template
 *   - Smart units: auto-detects recipient region (US field / SI metric)
 *
 * Implementation Plan:
 *   1. Outlook Add-in (Office.js MailApp API)
 *   2. Compose-mode task pane (insert calculation summaries into body)
 *   3. Read-mode task pane (parse P365 data from received emails)
 *   4. HTML table formatter for calculation results
 *   5. Attachment generation (pipe sizing PDF via browser print API)
 *
 * Architecture:
 *   src/addins/outlook/
 *     taskpane.html       — Outlook task pane entry point
 *     taskpane.tsx        — React: compose + read mode views
 *     formatter.ts        — HTML email table builder
 *     templates/
 *       pipe-sizing-email.ts  — Pipe sizing email template
 *       well-summary-email.ts — Well performance email template
 *     commands.ts         — Ribbon command handlers
 *
 * Office API Requirements:
 *   @microsoft/office-js >= 1.1
 *   Outlook API 1.6+ (for compose mode body manipulation)
 *   Permission: ReadWriteItem
 *
 * Manifest entry (outlook-manifest.xml):
 *   <Host Name="Mailbox" />
 *   <Rule xsi:type="RuleCollection" Mode="Or">
 *     <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
 *   </Rule>
 */

// ─── Email Template Definitions ───────────────────────────────────────────────

/** Available Outlook email templates. */
export const OUTLOOK_TEMPLATES = [
  {
    id:          "pipe-sizing-summary",
    name:        "Pipe Sizing Summary Email",
    description: "Auto-fill a professional pipe sizing result email with HTML table",
    subject:     "P365 Pipe Sizing Results — {job_name}",
  },
  {
    id:          "well-performance-summary",
    name:        "Well Performance Summary Email",
    description: "IPR + VLP nodal analysis results formatted for email",
    subject:     "P365 Well Performance Summary — {well_name}",
  },
  {
    id:          "gas-composition-report",
    name:        "Gas Composition Report Email",
    description: "Gas composition with HHV, LHV, Wobbe index, MW summary",
    subject:     "P365 Gas Analysis Report — {sample_id}",
  },
  {
    id:          "rfi-response",
    name:        "RFI Response with Calculations",
    description: "Request for Information response with embedded P365 calculations",
    subject:     "RE: {rfi_number} — P365 Engineering Response",
  },
] as const;

export type OutlookTemplateId = typeof OUTLOOK_TEMPLATES[number]["id"];

// ─── HTML Email Formatters ────────────────────────────────────────────────────

/** Build an HTML table for an email body from key-value pairs. */
export function buildEmailHtmlTable(
  title: string,
  rows: Record<string, string>,
  headerColor = "#1a5276",
): string {
  const rowHtml = Object.entries(rows)
    .map(([k, v]) => `<tr><td style="padding:4px 8px;border:1px solid #ccc;font-weight:bold">${k}</td>
      <td style="padding:4px 8px;border:1px solid #ccc">${v}</td></tr>`)
    .join("\n");

  return `
<table style="border-collapse:collapse;font-family:Calibri,Arial,sans-serif;font-size:11pt;min-width:400px">
  <thead>
    <tr><th colspan="2" style="background:${headerColor};color:white;padding:8px;text-align:left">${title}</th></tr>
    <tr>
      <th style="padding:4px 8px;border:1px solid #ccc;background:#d6eaf8;text-align:left">Parameter</th>
      <th style="padding:4px 8px;border:1px solid #ccc;background:#d6eaf8;text-align:left">Value</th>
    </tr>
  </thead>
  <tbody>${rowHtml}</tbody>
</table>
<p style="font-size:9pt;color:#666;margin-top:4px">
  <em>Generated by Petroleum 365 (P365) — petroleum engineering add-in</em>
</p>`.trim();
}

/** Build a pipe sizing email body. */
export function buildPipeSizingEmailBody(params: {
  jobName: string;
  results: Record<string, string>;
  notes?: string;
}): { subject: string; htmlBody: string } {
  const subject = `P365 Pipe Sizing Results — ${params.jobName}`;
  const table   = buildEmailHtmlTable("Pipe Sizing Results (Petroleum 365)", params.results);
  const notes   = params.notes
    ? `<p><strong>Notes:</strong> ${params.notes}</p>`
    : "";

  const htmlBody = `
<p>Please find the P365 pipe sizing calculation results below.</p>
${table}
${notes}
<p>All calculations performed using the Weymouth equation per AGA / NFPA 54 standards.<br>
Contact the engineering team for questions or to request the full calculation package.</p>`.trim();

  return { subject, htmlBody };
}

// ─── Well Performance Email ───────────────────────────────────────────────────

/** Build a well performance summary email body. */
export function buildWellPerformanceEmailBody(params: {
  wellName: string;
  reservoirPressure_psia: number;
  operatingRate_STBd: number;
  operatingPwf_psia: number;
  skin: number;
  pi_STBdPsi: number;
  qMax_STBd: number;
  notes?: string;
}): { subject: string; htmlBody: string } {
  const subject = `P365 Well Performance Summary — ${params.wellName}`;
  const rows: Record<string, string> = {
    "Well Name":                    params.wellName,
    "Reservoir Pressure (psia)":    params.reservoirPressure_psia.toFixed(1),
    "Operating Rate (STB/d)":       params.operatingRate_STBd.toFixed(1),
    "Operating Pwf (psia)":         params.operatingPwf_psia.toFixed(1),
    "Skin Factor":                  params.skin.toFixed(2),
    "PI (STB/d·psi)":               params.pi_STBdPsi.toFixed(4),
    "AOF / qMax (STB/d)":           params.qMax_STBd.toFixed(1),
  };
  const table = buildEmailHtmlTable("Well Performance Results (Petroleum 365)", rows, "#1a5276");
  const notes = params.notes ? `<p><strong>Notes:</strong> ${params.notes}</p>` : "";

  const htmlBody = `
<p>Please find the P365 well performance calculation results below.</p>
${table}
${notes}
<p>IPR analysis performed using the Vogel correlation. Contact the reservoir engineering team for questions.</p>`.trim();

  return { subject, htmlBody };
}

// ─── Gas Composition Email ────────────────────────────────────────────────────

/** Build a gas composition report email body. */
export function buildGasCompositionEmailBody(params: {
  sampleId: string;
  molarMass_lbMol: number;
  specificGravity: number;
  hhv_BTUscf: number;
  lhv_BTUscf: number;
  wobbeIndex: number;
  notes?: string;
}): { subject: string; htmlBody: string } {
  const subject = `P365 Gas Analysis Report — ${params.sampleId}`;
  const rows: Record<string, string> = {
    "Sample ID":                params.sampleId,
    "Molar Mass (lb/lb-mol)":   params.molarMass_lbMol.toFixed(3),
    "Specific Gravity (air=1)": params.specificGravity.toFixed(4),
    "HHV (BTU/scf)":            params.hhv_BTUscf.toFixed(2),
    "LHV (BTU/scf)":            params.lhv_BTUscf.toFixed(2),
    "Wobbe Index":               params.wobbeIndex.toFixed(2),
  };
  const table = buildEmailHtmlTable("Gas Composition Report (Petroleum 365)", rows, "#1a5276");
  const notes = params.notes ? `<p><strong>Notes:</strong> ${params.notes}</p>` : "";

  const htmlBody = `
<p>Please find the P365 gas composition analysis results below.</p>
${table}
${notes}
<p>All calorific values are on a dry basis at 60 °F / 14.73 psia. Generated by Petroleum 365.</p>`.trim();

  return { subject, htmlBody };
}

// ─── RFI Response Email ───────────────────────────────────────────────────────

/** Build an RFI response email with embedded calculation table. */
export function buildRfiResponseEmailBody(params: {
  rfiNumber: string;
  subject: string;
  calcType: string;
  summaryRows: Record<string, string>;
  engineerName: string;
  notes?: string;
}): { subject: string; htmlBody: string } {
  const subject = `RE: ${params.rfiNumber} — P365 Engineering Response`;
  const table = buildEmailHtmlTable(
    `${params.calcType} — Calculation Summary (Petroleum 365)`,
    params.summaryRows,
    "#154360",
  );
  const notes = params.notes ? `<p><strong>Notes:</strong> ${params.notes}</p>` : "";

  const htmlBody = `
<p>Dear Team,</p>
<p>Please find our engineering response to <strong>${params.rfiNumber}</strong> — ${params.subject} below.</p>
${table}
${notes}
<p>Prepared by: ${params.engineerName}<br>
Calculations performed using Petroleum 365 (P365). Please reach out with any questions.</p>`.trim();

  return { subject, htmlBody };
}

// ─── DCA Forecast Email ───────────────────────────────────────────────────────

/** Build a DCA forecast email body. */
export function buildDcaForecastEmailBody(params: {
  wellName: string;
  model: string;
  qi_STBd: number;
  di_pct: number;
  b_factor: number;
  eur_MBbl: number;
  forecastYears: number;
  notes?: string;
}): { subject: string; htmlBody: string } {
  const subject = `P365 DCA Forecast — ${params.wellName}`;
  const rows: Record<string, string> = {
    "Well Name":            params.wellName,
    "Decline Model":        params.model,
    "Initial Rate qi (STB/d)": params.qi_STBd.toFixed(1),
    "Initial Decline Di (%)":  params.di_pct.toFixed(2),
    "Hyperbolic b-factor":  params.b_factor.toFixed(3),
    "EUR (MBbl)":           params.eur_MBbl.toFixed(1),
    "Forecast Period (yr)": params.forecastYears.toString(),
  };
  const table = buildEmailHtmlTable("DCA Forecast Results (Petroleum 365)", rows, "#1a5276");
  const notes = params.notes ? `<p><strong>Notes:</strong> ${params.notes}</p>` : "";

  const htmlBody = `
<p>Please find the P365 decline curve analysis forecast results below.</p>
${table}
${notes}
<p>Forecast generated using the Arps decline curve model. EUR is estimated to economic limit.</p>`.trim();

  return { subject, htmlBody };
}

// ─── Unit System Detection ────────────────────────────────────────────────────

/** Metric TLDs / domain fragments. */
const METRIC_TLDS = new Set([".ca", ".uk", ".au", ".nl", ".no", ".de", ".fr", ".it", ".es", ".mx", ".br", ".ar", ".co"]);

/**
 * Detect whether an email address belongs to a metric-using region.
 * Returns "metric" if the domain matches a known metric TLD or contains "intl";
 * otherwise returns "field".
 */
export function detectUnitSystem(recipientEmail: string): "field" | "metric" {
  const domain = recipientEmail.split("@")[1] ?? "";
  const lower  = domain.toLowerCase();

  if (lower.includes("intl")) return "metric";

  for (const tld of METRIC_TLDS) {
    if (lower.endsWith(tld)) return "metric";
  }

  return "field";
}

// ─── Value Conversion for Email ───────────────────────────────────────────────

/** Conversion factors from field to metric units. */
const UNIT_CONVERSIONS: Record<string, { factor: number; metricUnit: string }> = {
  psia:   { factor: 6.89476,  metricUnit: "kPa"  },
  psig:   { factor: 6.89476,  metricUnit: "kPa"  },
  ft:     { factor: 0.3048,   metricUnit: "m"    },
  STBd:   { factor: 0.158987, metricUnit: "m3/d" },
  "m3d":  { factor: 1,        metricUnit: "m3/d" },
  BTU:    { factor: 1.05506,  metricUnit: "kJ"   },
  "BTU/scf": { factor: 37.2589, metricUnit: "kJ/m3" },
  "lb/ft3":  { factor: 16.0185, metricUnit: "kg/m3" },
  "°F":   { factor: 1,        metricUnit: "°C"   }, // handled specially
};

/**
 * Convert a numeric value and its unit to the target unit system.
 * If system is "field", returns the value and unit unchanged.
 * If system is "metric", applies known conversion factors.
 */
export function convertValueForEmail(
  value: number,
  unit: string,
  system: "field" | "metric",
): { value: number; unit: string } {
  if (system === "field") return { value, unit };

  // Special case: Fahrenheit → Celsius
  if (unit === "°F") {
    return { value: (value - 32) * (5 / 9), unit: "°C" };
  }

  const conv = UNIT_CONVERSIONS[unit];
  if (conv) {
    return { value: value * conv.factor, unit: conv.metricUnit };
  }

  // No conversion known — return unchanged
  return { value, unit };
}
