/**
 * P365 Outlook Add-in — MailApp Plug-in
 *
 * Auto-generates petroleum engineering calculation summaries as formatted
 * emails from P365 calculation results.
 *
 * Planned Features:
 *   - Insert pipe sizing summary into email body (HTML table)
 *   - Auto-generate RFI response with calculation attachments
 *   - P365 calculation snapshot to email (read-only results card)
 *   - Gas composition report via email
 *   - Well performance summary email template
 *   - Smart units: auto-detects recipient region (US field / SI metric)
 *
 * Implementation Plan:
 *   1. Outlook Add-in (Office.js MailApp API)
 *   2. Compose-mode task pane (insert calculation summaries into body)
 *   3. Read-mode task pane (parse P365 data from received emails)
 *   4. HTML table formatter for calculation results
 *   5. Attachment generation (pipe sizing PDF via browser print API)
 *
 * Architecture:
 *   src/addins/outlook/
 *     taskpane.html       — Outlook task pane entry point
 *     taskpane.tsx        — React: compose + read mode views
 *     formatter.ts        — HTML email table builder
 *     templates/
 *       pipe-sizing-email.ts  — Pipe sizing email template
 *       well-summary-email.ts — Well performance email template
 *     commands.ts         — Ribbon command handlers
 *
 * Office API Requirements:
 *   @microsoft/office-js >= 1.1
 *   Outlook API 1.6+ (for compose mode body manipulation)
 *   Permission: ReadWriteItem
 *
 * Manifest entry (outlook-manifest.xml):
 *   <Host Name="Mailbox" />
 *   <Rule xsi:type="RuleCollection" Mode="Or">
 *     <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
 *   </Rule>
 */

// ─── Email Template Definitions ───────────────────────────────────────────────

/** Available Outlook email templates. */
export const OUTLOOK_TEMPLATES = [
  {
    id:          "pipe-sizing-summary",
    name:        "Pipe Sizing Summary Email",
    description: "Auto-fill a professional pipe sizing result email with HTML table",
    subject:     "P365 Pipe Sizing Results — {job_name}",
  },
  {
    id:          "well-performance-summary",
    name:        "Well Performance Summary Email",
    description: "IPR + VLP nodal analysis results formatted for email",
    subject:     "P365 Well Performance Summary — {well_name}",
  },
  {
    id:          "gas-composition-report",
    name:        "Gas Composition Report Email",
    description: "Gas composition with HHV, LHV, Wobbe index, MW summary",
    subject:     "P365 Gas Analysis Report — {sample_id}",
  },
  {
    id:          "rfi-response",
    name:        "RFI Response with Calculations",
    description: "Request for Information response with embedded P365 calculations",
    subject:     "RE: {rfi_number} — P365 Engineering Response",
  },
] as const;

export type OutlookTemplateId = typeof OUTLOOK_TEMPLATES[number]["id"];

// ─── HTML Email Formatters ────────────────────────────────────────────────────

/** Build an HTML table for an email body from key-value pairs. */
export function buildEmailHtmlTable(
  title: string,
  rows: Record<string, string>,
  headerColor = "#1a5276",
): string {
  const rowHtml = Object.entries(rows)
    .map(([k, v]) => `<tr><td style="padding:4px 8px;border:1px solid #ccc;font-weight:bold">${k}</td>
      <td style="padding:4px 8px;border:1px solid #ccc">${v}</td></tr>`)
    .join("\n");

  return `
<table style="border-collapse:collapse;font-family:Calibri,Arial,sans-serif;font-size:11pt;min-width:400px">
  <thead>
    <tr><th colspan="2" style="background:${headerColor};color:white;padding:8px;text-align:left">${title}</th></tr>
    <tr>
      <th style="padding:4px 8px;border:1px solid #ccc;background:#d6eaf8;text-align:left">Parameter</th>
      <th style="padding:4px 8px;border:1px solid #ccc;background:#d6eaf8;text-align:left">Value</th>
    </tr>
  </thead>
  <tbody>${rowHtml}</tbody>
</table>
<p style="font-size:9pt;color:#666;margin-top:4px">
  <em>Generated by Petroleum 365 (P365) — petroleum engineering add-in</em>
</p>`.trim();
}

/** Build a pipe sizing email body. */
export function buildPipeSizingEmailBody(params: {
  jobName: string;
  results: Record<string, string>;
  notes?: string;
}): { subject: string; htmlBody: string } {
  const subject = `P365 Pipe Sizing Results — ${params.jobName}`;
  const table   = buildEmailHtmlTable("Pipe Sizing Results (Petroleum 365)", params.results);
  const notes   = params.notes
    ? `<p><strong>Notes:</strong> ${params.notes}</p>`
    : "";

  const htmlBody = `
<p>Please find the P365 pipe sizing calculation results below.</p>
${table}
${notes}
<p>All calculations performed using the Weymouth equation per AGA / NFPA 54 standards.<br>
Contact the engineering team for questions or to request the full calculation package.</p>`.trim();

  return { subject, htmlBody };
}
