/**
 * P365 OneNote Add-in — Notebook Plug-in
 *
 * Inserts P365 calculation results into OneNote notebook pages for
 * field engineers, O&M teams, and project documentation.
 *
 * Planned Features:
 *   - Insert P365 calculation block into a OneNote page (table + results)
 *   - Create a "P365 Job Log" notebook section automatically
 *   - Pipe sizing result block (with inline unit conversions)
 *   - Well performance snapshot (rate, pressure, skin)
 *   - Gas composition analysis block
 *   - PTA interpretation notes (permeability, skin, PI)
 *   - Field measurement log (date/time-stamped entries)
 *
 * Implementation Plan:
 *   1. Office.js OneNote API task pane (React)
 *   2. OneNote Page HTML content insertion (insertHtmlContent)
 *   3. Structured note blocks with P365 results as HTML tables
 *   4. Auto-create sections: "Pipe Sizing", "Well Tests", "PVT Data"
 *   5. Cross-reference with Excel workbook (via Office shared runtime)
 *
 * Architecture:
 *   src/addins/onenote/
 *     taskpane.html          — OneNote task pane entry
 *     taskpane.tsx           — React: note block builder
 *     blocks/
 *       pipe-sizing-block.ts — HTML block for pipe sizing notes
 *       well-log-block.ts    — HTML block for well test notes
 *       pvt-block.ts         — HTML block for PVT data
 *       composition-block.ts — HTML block for gas composition
 *     commands.ts            — Ribbon command handlers
 *
 * Office API Requirements:
 *   @microsoft/office-js >= 1.1
 *   OneNote API 1.1+
 *   Permission: ReadWriteDocument
 *
 * Manifest entry (onenote-manifest.xml):
 *   <Host Name="Notebook" />
 */

// ─── Note Block Definitions ───────────────────────────────────────────────────

/** Available OneNote note block types. */
export const ONENOTE_BLOCKS = [
  {
    id:          "pipe-sizing-note",
    name:        "Pipe Sizing Note",
    description: "Insert a formatted pipe sizing calculation result block",
    icon:        "🔧",
  },
  {
    id:          "well-performance-note",
    name:        "Well Performance Note",
    description: "Insert IPR + VLP well performance summary with key metrics",
    icon:        "🛢",
  },
  {
    id:          "gas-composition-note",
    name:        "Gas Composition Note",
    description: "Insert gas composition analysis: MW, SG, HHV, LHV, Wobbe",
    icon:        "⚗️",
  },
  {
    id:          "well-test-note",
    name:        "Well Test Note",
    description: "Insert PTA interpretation: k, S, P*, Horner plot summary",
    icon:        "📊",
  },
  {
    id:          "field-measurement-log",
    name:        "Field Measurement Log",
    description: "Timestamped field measurement entry (pressure, rate, temp)",
    icon:        "📋",
  },
] as const;

export type OneNoteBlockId = typeof ONENOTE_BLOCKS[number]["id"];

// ─── HTML Block Builders ──────────────────────────────────────────────────────

/**
 * Build OneNote HTML for a calculation note block.
 * OneNote page HTML is inserted via the Page.insertHtmlContent API.
 *
 * @param title       Block title (e.g., "Pipe Sizing — Job #12345")
 * @param rows        Key-value results
 * @param timestamp   ISO timestamp string
 * @param notes       Optional engineer notes
 * @returns           HTML string suitable for OneNote page insertion
 */
export function buildOneNoteBlock(
  title: string,
  rows: Record<string, string>,
  timestamp: string,
  notes?: string,
): string {
  const rowHtml = Object.entries(rows)
    .map(([k, v]) => `<tr><td><b>${k}</b></td><td>${v}</td></tr>`)
    .join("");

  const notesHtml = notes
    ? `<p><b>Notes:</b> ${notes}</p>`
    : "";

  return `
<div>
  <h2>${title}</h2>
  <p><i>Generated by Petroleum 365 (P365) — ${timestamp}</i></p>
  <table border="1" style="border-collapse:collapse;font-family:Calibri,sans-serif">
    <tr>
      <th style="background:#1a5276;color:white;padding:4px 8px">Parameter</th>
      <th style="background:#1a5276;color:white;padding:4px 8px">Value</th>
    </tr>
    ${rowHtml}
  </table>
  ${notesHtml}
</div>`.trim();
}

/**
 * Build a field measurement log entry for OneNote.
 *
 * @param wellName    Well or location name
 * @param timestamp   Measurement timestamp (ISO string)
 * @param measurements  Measured values
 * @param engineer    Engineer's name
 * @returns           HTML suitable for OneNote page insertion
 */
export function buildFieldMeasurementLog(
  wellName: string,
  timestamp: string,
  measurements: Array<{ parameter: string; value: number; unit: string }>,
  engineer: string,
): string {
  const rowHtml = measurements
    .map(m => `<tr><td>${m.parameter}</td><td>${m.value} ${m.unit}</td></tr>`)
    .join("");

  return `
<div>
  <h3>📋 Field Measurement Log — ${wellName}</h3>
  <p><b>Date/Time:</b> ${timestamp} | <b>Recorded by:</b> ${engineer}</p>
  <table border="1" style="border-collapse:collapse;font-family:Calibri,sans-serif;min-width:300px">
    <tr>
      <th style="background:#2e86c1;color:white;padding:4px 8px">Parameter</th>
      <th style="background:#2e86c1;color:white;padding:4px 8px">Measured Value</th>
    </tr>
    ${rowHtml}
  </table>
  <p><i>Recorded with Petroleum 365 (P365)</i></p>
</div>`.trim();
}

// ─── Additional Note Block Builders ──────────────────────────────────────────

/**
 * Build a PVT data block for OneNote.
 */
export function buildPvtDataBlock(params: {
  wellName: string;
  timestamp: string;
  pressure_psia: number;
  temp_F: number;
  zFactor: number;
  bg_rcf_scf: number;
  bo_rbStb: number;
  hhv_BTUscf: number;
  notes?: string;
}): string {
  return buildOneNoteBlock(
    `PVT Data — ${params.wellName}`,
    {
      "Well Name":      params.wellName,
      "Pressure":       `${params.pressure_psia.toFixed(1)} psia`,
      "Temperature":    `${params.temp_F.toFixed(1)} °F`,
      "Z-Factor":       params.zFactor.toFixed(4),
      "Bg":             `${params.bg_rcf_scf.toFixed(5)} rcf/scf`,
      "Bo":             `${params.bo_rbStb.toFixed(4)} rb/STB`,
      "HHV":            `${params.hhv_BTUscf.toFixed(2)} BTU/scf`,
    },
    params.timestamp,
    params.notes,
  );
}

/**
 * Build a gas composition block for OneNote.
 */
export function buildGasCompositionBlock(params: {
  sampleId: string;
  timestamp: string;
  molarMass_lbMol: number;
  specificGravity: number;
  hhv_BTUscf: number;
  lhv_BTUscf: number;
  wobbeIndex: number;
  co2_mol?: number;
  h2s_mol?: number;
  notes?: string;
}): string {
  const rows: Record<string, string> = {
    "Sample ID":       params.sampleId,
    "Molar Mass":      `${params.molarMass_lbMol.toFixed(3)} lb/mol`,
    "Specific Gravity": params.specificGravity.toFixed(4),
    "HHV":             `${params.hhv_BTUscf.toFixed(2)} BTU/scf`,
    "LHV":             `${params.lhv_BTUscf.toFixed(2)} BTU/scf`,
    "Wobbe Index":     `${params.wobbeIndex.toFixed(2)} BTU/scf`,
  };
  if (params.co2_mol !== undefined) rows["CO2"] = `${params.co2_mol.toFixed(2)} mol%`;
  if (params.h2s_mol !== undefined) rows["H2S"] = `${params.h2s_mol.toFixed(2)} mol%`;

  return buildOneNoteBlock(`Gas Composition — ${params.sampleId}`, rows, params.timestamp, params.notes);
}

/**
 * Build a well test interpretation block for OneNote.
 */
export function buildWellTestBlock(params: {
  wellName: string;
  testDate: string;
  producingTime_hr: number;
  flowRate_STBd: number;
  permeability_md: number;
  skin: number;
  pStar_psia: number;
  reservoirPressure_psia: number;
  notes?: string;
}): string {
  return buildOneNoteBlock(
    `Well Test — ${params.wellName}`,
    {
      "Well Name":           params.wellName,
      "Test Date":           params.testDate,
      "Producing Time":      `${params.producingTime_hr.toFixed(1)} hr`,
      "Flow Rate":           `${params.flowRate_STBd.toFixed(0)} STB/d`,
      "Permeability":        `${params.permeability_md.toFixed(2)} md`,
      "Skin":                params.skin.toFixed(2),
      "P* (extrapolated)":   `${params.pStar_psia.toFixed(1)} psia`,
      "Reservoir Pressure":  `${params.reservoirPressure_psia.toFixed(1)} psia`,
    },
    params.testDate,
    params.notes,
  );
}

/**
 * Build a well performance block for OneNote.
 */
export function buildWellPerformanceBlock(params: {
  wellName: string;
  timestamp: string;
  operatingRate_STBd: number;
  operatingPwf_psia: number;
  reservoirPressure_psia: number;
  skin: number;
  pi_STBdPsi: number;
  notes?: string;
}): string {
  return buildOneNoteBlock(
    `Well Performance — ${params.wellName}`,
    {
      "Well Name":           params.wellName,
      "Operating Rate":      `${params.operatingRate_STBd.toFixed(0)} STB/d`,
      "Operating Pwf":       `${params.operatingPwf_psia.toFixed(1)} psia`,
      "Reservoir Pressure":  `${params.reservoirPressure_psia.toFixed(1)} psia`,
      "Skin":                params.skin.toFixed(2),
      "Productivity Index":  `${params.pi_STBdPsi.toFixed(3)} STB/d/psi`,
    },
    params.timestamp,
    params.notes,
  );
}

/**
 * Build a DCA forecast block for OneNote.
 */
export function buildDcaForecastBlock(params: {
  wellName: string;
  timestamp: string;
  model: string;
  qi_STBd: number;
  di_pct: number;
  b_factor: number;
  eur_MBbl: number;
  forecastYears: number;
  notes?: string;
}): string {
  return buildOneNoteBlock(
    `DCA Forecast — ${params.wellName}`,
    {
      "Well Name":       params.wellName,
      "Model":           params.model,
      "Initial Rate":    `${params.qi_STBd.toFixed(0)} STB/d`,
      "Decline Rate":    `${params.di_pct.toFixed(2)}%/yr`,
      "b-factor":        params.b_factor.toFixed(3),
      "EUR":             `${params.eur_MBbl.toFixed(1)} MBbl`,
      "Forecast Period": `${params.forecastYears} yr`,
    },
    params.timestamp,
    params.notes,
  );
}

/**
 * Build a complete OneNote page HTML combining multiple note blocks.
 */
export function buildJobSummaryPage(params: {
  jobNumber: string;
  projectName: string;
  client: string;
  engineer: string;
  date: string;
  location: string;
  blocks: string[];
}): string {
  const metaRows = [
    ["Job Number", params.jobNumber],
    ["Project Name", params.projectName],
    ["Client", params.client],
    ["Engineer", params.engineer],
    ["Date", params.date],
    ["Location", params.location],
  ]
    .map(([k, v]) => `<tr><td><b>${k}</b></td><td>${v}</td></tr>`)
    .join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>${params.projectName} — ${params.jobNumber}</title></head>
<body style="font-family:Calibri,sans-serif">
  <h1>Job Summary — ${params.projectName}</h1>
  <table border="1" style="border-collapse:collapse;margin-bottom:16px">
    <tr>
      <th style="background:#1a5276;color:white;padding:4px 8px">Field</th>
      <th style="background:#1a5276;color:white;padding:4px 8px">Value</th>
    </tr>
    ${metaRows}
  </table>
  ${params.blocks.join("\n  ")}
</body>
</html>`.trim();
}
